name: Robot Framework Testes API
on: push
jobs:
  test:
    name: Run Testes
    runs-on: ubuntu-latest

    steps:
    - name: checkout Repository #Clonar arquivos
      uses: actions/checkout@v2

    - name: Set up Python #Configurar python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run:  |
        pip install robotframework
        pip install robotframework-requests
        pip install robotframework-faker
        python3 -m pip install robotframework-seleniumlibrary
        python -m pip install robotframework-seleniumlibrary
        pip install --upgrade robotframework-seleniumlibrary
        pip3 install --upgrade robotframework-seleniumlibrary

    - name: Run Robot Frameworks testes
      run:  |
        robot -d .\logs\crud  testes/crud.robot
    - name: Arquive Robot Framework results #Salvar resultados
      if: ${{always() }}
      uses: actions/upload-artifact@v3
      with:
        name: robot-results
        path: ./results
